import CardUi from '@/components/CardUi';
import Navbar from '@/components/Navbar';
import { auth, storage } from '@/firebase/clientApp';
import { Box, Image, SimpleGrid } from '@chakra-ui/react'
import { getDownloadURL, listAll, ref } from 'firebase/storage';
import Head from 'next/head'
import { useEffect, useState } from 'react';
import { useAuthState } from 'react-firebase-hooks/auth';
import { useDownloadURL } from 'react-firebase-hooks/storage';

export default function Home() {
  const [imageUrls, setImageUrls] = useState([]);
  useEffect(() => {
    listAll(ref(storage, 'images/')).then((response) => {
      response.items.forEach((item) => {
        getDownloadURL(item).then((url) => {
          setImageUrls((prev) => [...prev, url as never]);
        });
      });
    });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <SimpleGrid spacing={30} p={10} pt={100} templateColumns='repeat(auto-fill, minmax(200px, 1fr))'>
      {imageUrls.map((url) => {
        return <CardUi key={url} url={url}/>;
      })}
      </SimpleGrid>
    </>
  )
}
